agregando ejercicios
jeffcorb/TareaTres pull request #1
Opened 2022-11-05 14:09 UTC by jeffcorb

Agregue los ejercicios 1 a 4

2022-11-05 14:29 UTC, calvarioTeacher31 commented on src/Ejercicio1.java
> +                System.out.println("\n");
qué quieres lograr con este \n?

2022-11-05 14:32 UTC, calvarioTeacher31 requested changes

2022-11-05 14:32 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +            }
esto lo tienes que generalizar usando try/catch y la excepción

2022-11-05 14:32 UTC, calvarioTeacher31 commented on src/Ejercicio4.java
> +        while (mapStock.containsKey(opcion));
- deja espacios para que no esté en un bloque apretado

2022-11-05 14:32 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +            System.out.println(list.indexOf(i) + "  " + i);
usa system.out.printf
para meterle enter al printf puedes usar un %n

2022-11-05 14:32 UTC, jeffcorb commented on src/Ejercicio1.java
> +                System.out.println("\n");
Darle mas espacio para que se vea mejor en consola la lista que viene luego

2022-11-08 04:46 UTC, calvarioTeacher31 requested changes

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio2.java
> +            System.out.println("Key: " + set.getKey() + " |  Value: " + set.getValue());
usa system.out.printf

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +            System.out.printf(list.indexOf(i) + "  " + i);
man esto no tiene sentido justamente printf es para que no uses el + xd

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio1.java
> +        while (!opcion.equals("Despedirse"));
te falta cerrar el scanner

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio2.java
> +        while (opcion != -1);
te falta cerra el scanner

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +
te falta cerrar el scanner

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +        } catch (ExcepcionRango e) {
revisa la tabla de excepciones cuál se puede usar... las excepciones no se crean se usan ya las existentes

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +    }
esto no tiene ni un puto sentido aea

2022-11-08 04:46 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +    }
no he enseñado esto, no tiene sentido

2022-11-15 16:29 UTC, calvarioTeacher31 approved these changes

2022-11-15 16:32 UTC, jeffcorb commented on src/Ejercicio1.java
> +        while (!opcion.equals("Despedirse"));
resuelto

2022-11-15 16:33 UTC, jeffcorb commented on src/Ejercicio3.java
> +
resuelto

2022-11-17 03:11 UTC, merged